const fileSystem = {
  'C:': {
    users: {},
  },
  'C:\\users': {
    coen: {},
  },
  'C:\\users\\coen': {
    repos: {},
  },
  'C:\\users\\coen\\repos': {
    website: {},
    zmov: {},
  },
  'C:\\users\\coen\\repos\\zmov': {
    public: {},
    screenshots: {},
    src: {},
    '.eslintrc.cjs': 'file',
    '.gitignore': 'file',
    'LICENSE': 'file',
    'README.md': 'file',
    'index.html': 'file',
    'package-lock.json': 'file',
    'package.json': 'file',
    'vercel.json': 'file',
    'vite.config.js': 'file',
  },
  'C:\\users\\coen\\repos\\zmov\\src': {
    assets: {},
    components: {},
    pages: {},
    utils: {},
    'App.jsx': 'file',
    'index.jsx': 'file',
    'index.css': 'file',
  },
  'C:\\users\\coen\\repos\\zmov\\src\\assets': {
    'icon.png': 'file',
    'logo.png': 'file',
  },
  'C:\\users\\coen\\repos\\zmov\\src\\components': {
    'Card.jsx': 'file',
    'Discover.jsx': 'file',
    'DmcaContent.jsx': 'file',
    'Footer.jsx': 'file',
    'Header.jsx': 'file',
    'Hero.jsx': 'file',
    'InfoContent.jsx': 'file',
    'InstallButton.jsx': 'file',
    'ServiceCard.jsx': 'file',
    'SettingsContent.jsx': 'file',
    'Watchlist.jsx': 'file',
    'WatchlistCard.jsx': 'file',
    'WideCard.jsx': 'file',
  },
  'C:\\users\\coen\\repos\\zmov\\src\\pages': {
    'Dmca.jsx': 'file',
    'Home.jsx': 'file',
    'Info.jsx': 'file',
    'NotFound.jsx': 'file',
    'Player.jsx': 'file',
    'Search.jsx': 'file',
    'Services.jsx': 'file',
    'Settings.jsx': 'file',
  },
  'C:\\users\\coen\\repos\\zmov\\src\\utils': {
    'ScrollToTopOnLoad.jsx': 'file',
  },
  'C:\\users\\coen\\repos\\zmov\\public': {
    images: {},
    'favicon.svg': 'file',
    'manifest.json': 'file',
    'pwa-192x192.png': 'file',
    'pwa-512x512.png': 'file',
    'robots.txt': 'file',
  },
  'C:\\users\\coen\\repos\\zmov\\public\\images': {
    'apple.svg': 'file',
    'disney.svg': 'file',
    'icon.svg': 'file',
    'logo.svg': 'file',
    'max.svg': 'file',
    'netflix.svg': 'file',
    'prime.svg': 'file',
  },
  'C:\\users\\coen\\repos\\zmov\\screenshots': {
    'home.png': 'file',
    'info.png': 'file',
    'mhome.png': 'file',
    'minfo.png': 'file',
    'msearch.png': 'file',
    'muser.png': 'file',
    'search.png': 'file',
    'user.png': 'file',
  },
  'C:\\users\\coen\\repos\\website': {
    public: {},
    src: {},
    '.eslintrc.cjs': 'file',
    '.gitignore': 'file',
    'index.html': 'file',
    'package-lock.json': 'file',
    'package.json': 'file',
    'README.md': 'file',
    'vite.config.js': 'file',
  },
  'C:\\users\\coen\\repos\\website\\public': {
    'empty.png': 'file',
  },
  'C:\\users\\coen\\repos\\website\\src': {
    components: {},
    'App.jsx': 'file',
    'index.css': 'file',
    'main.jsx': 'file',
  },
  'C:\\users\\coen\\repos\\website\\src\\components': {
    'Terminal.jsx': 'file'
  }
};

export default fileSystem;